SELECT *
FROM JAVA_MEMBER
WHERE ID = 'admin'
AND PASS = '1234'
AND DELYN = 'N'
AND ROLE = 2;

SELECT *
FROM JAVA_PROD;

-- 상세 추가
SELECT NVL(MAX(NO),0) + 1
FROM JAVA_PROD;

INSERT INTO JAVA_PROD
VALUES((SELECT NVL(MAX(NO),0) + 1 FROM JAVA_PROD), '이름', '타입', 100000, 'N');

UPDATE JAVA_PROD
SET DELYN = 'Y'
WHERE NO = 1;

UPDATE JAVA_PROD
SET NAME = '이름', 
    TYPE = '타입',
    PRICE = 10000
WHERE NO = 1;